source.. = src/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               css/default.css,\
               Application.e4xmi,\
               lib/,\
               lib/gson-2.8.6.jar,\
               lib/javacsv.jar,\
               lib/xmlbeans-3.1.0.jar,\
               lib/xmlschema-core-2.2.1.jar,\
               lib/commons-collections4-4.1.jar,\
               lib/commons-compress-1.18.jar,\
               lib/nlteckSWTLib.v1.0.0.jar,\
               lib/nltecklib.v1.0.6.jar
